# pod-nginx-required-affinity.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  # affinity
  affinity:
    nodeAffinity:
      # required
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        # disktype이 ssd인 node에 파드 생성
        - matchExpressions:
          - key: cloud_type
            operator: In
            values: 
            - AWS
            
      preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                - key: preferredkey1
                  operator: In
                  values: 
                  - prefereedvalue1
                  
      preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 30
              preference:
                matchExpressions:
                - key: preferredkey2
                  operator: In
                  values: 
                  - prefereedvalue2          
                  
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
