kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker01-pvc02
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: worker01-pv02 
