kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker02-pvc04
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: worker02-pv04