apiVersion: v1
kind: Pod
metadata:
  name: worker03-pv05-pod
  labels:
    name: worker03-pv05-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo "The local volume(worker03-pv05) is mounted!" > /mnt/test.txt && sleep 3600']
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /mnt
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: worker03-pvc05

