apiVersion: v1
kind: Pod
metadata:
  name: delete-pod
  labels:
    name: delete
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo "The local volume(delete) is again mounted!" > /mnt/delete2.txt && sleep 3600']
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /mnt
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: delete-pvc
