kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: delete-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: delete
